{{- $pdb := .Values.podDisruptionBudget | default dict }}
{{- if $pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-service.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "hello-service.labels" . | nindent 4 }}
spec:
  {{- with $pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with $pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hello-service.selectorLabels" . | nindent 6 }}
{{- end }}
